### ISSUE TITLE
Fix typeface.yml format

### ISSUE THREAD

**Issue by 3846masa** [Japont/typeface#1]
適当だったので，こうしたい

```yaml
name: example
family: Example Font
designers:
  - John Smith
website: https://example.com
sources:
  - url: https://example.com/files.zip
    files:
      - '**/example.ttf'
license:
  type: SPDX Identifier or Mplus or Others
  sources:
    - url: https://example.com/files.zip
      files:
        - '**/LICENSE'
category: SERIF or SANSSERIF or MINCHO or GOTHIC or OTHERS
copyrights:
  - Copyright (c) 2016 John Smith
```
